### PR TITLE
Update package_installs.R

### PR DESCRIPTION
**Pull request by jsylas**
Added a new package on computer vision & image recognition

### CODE REVIEW

**Comment by amrrs** [comment]
I guess, the package that you are referring to is not right, that's the repo where collection of other packages are there. Please check @jsylas  @

**Comment by jsylas** [comment]
I need the following  package from this path image.darknet,image.CannyEdges ,image.ContourDetector ,image.CornerDetectionF9 ,image.DenoiseNLMeans ,image.LineSegmentDetector  and image.dlib. could you please can make it available.

**Comment by amrrs** [comment]
@jsylas i tried so much to make `image.darknet` available. I even uploaded a private dataset making a package but that didn't work either. Then i made a binary build of the development version package and use it, but because my machine is mac and Kaggler docker is linux, it didn't work either. If you have a linux machine, you can make binary build and then upload it on Kaggle as private dataset and use local installation.

**Comment by jsylas** [comment]
@amrrs I did not have Linux and especially require the image.darknet. Could you please suggest others ways to make it available.

**Comment by amrrs** [comment]
You can use it without Kaggle.

Are you specifically looking for it in Kaggle kernel?
On Aug 6, 2018, at 20:46, jsylas <notifications@github.com<mailto:notifications@github.com>> wrote:

@amrrs<https://github.com/amrrs> I did not have Linux and especially require the image.darknet. Could you please suggest others ways to make it available.

**Comment by jsylas** [comment]
@amrrs Yes , specifically looking it in kaggle kernel to execute thru kaggle kernel.

**Comment by amrrs** [comment]
@jsylas  i think only Kaggle team can help you then. I'd suggest you find someone's email id and email them. Also would you be interested in sharing with me the purpose either on an email or here, because I've used `image.darknet` for one of my recent blogposts and interesed in that.

**Comment by Philmod** [comment]
Please add a unit test to make sure the new package works as expected.

**Pull request closed without merging**
