### PR TITLE
Unpin notebook.

### PR DESCRIPTION
**Pull request by jplotts**
The referenced issue is closed.

http://b/211487924

### CODE REVIEW

**Comment by Philmod** [comment]
It's going to be tricky to merge this PR before we fix another issue that started on Feb 21. Just created a bug for it: https://b.corp.google.com/issues/224540778

**Comment by Philmod** [comment]
I merged my [branch](https://github.com/Kaggle/docker-rstats/pull/181) here which has 2 fixes for the CPU build.

**Comment by jplotts** [comment]
@Philmod - tests pass now with your fixes, thanks!  Wdyt about merging this?

**Comment by Philmod** [comment]
> @Philmod - tests pass now with your fixes, thanks! Wdyt about merging this?

Were you able to test it on kaggle?
The problem is the GPU build is broken, so we wouldn't be able to deploy these new images. Is that ok?

**Comment by jplotts** [comment]
Yes, it seems to pass basic smoke tests: https://screenshot.googleplex.com/93eHpNq3mnMnj75

How long until we can deploy new GPU images?  At some point, they will have to be deployed right?  The R autocomplete work will be blocked until then.

**Comment by jplotts** [comment]
@Philmod - friendly ping

**Review by Philmod — APPROVED** [review]

**Pull request merged**
